#### Rooms ####

GET http://localhost:8181/hotels/5/rooms

###

POST http://localhost:8181/hotels/5/rooms
content-type: application/json

{
    "number": "503",
    "pricePerDay": "150",
    "amountOfPeople": "2",
    "state": "1"
}
###
PUT http://localhost:8181/hotels/3/rooms/42
content-type: application/json

{
    "number": "11",
    "pricePerDay": "120",
    "amountOfPeople": "2",
    "state": "3"
}
###
DELETE http://localhost:8181/hotels/3/rooms/43


#### Hotels ####

GET http://localhost:8181/hotels

###
GET http://localhost:8181/hotels/3
###
POST http://localhost:8181/hotels
content-type: application/json

{
  "name": "Imperial Hotel",
  "city": "Krakow",
  "streetAndNumber": "ul.Hotelowa 34",
  "postalCode": "31-007",
  "phoneNumber": "+48 969-010-749"
}
###
PUT http://localhost:8181/hotels/3
content-type: application/json

{
  "id": 3,
  "name": "Imperial Hotel",
  "city": "Krakow",
  "streetAndNumber": "ul.Hotelowa 34",
  "postalCode": "31-007",
  "phoneNumber": "+48 969-010-749"
}
###
DELETE http://localhost:8181/hotels/3

### Auth ###
POST http://localhost:8181/sign-up
content-type: application/json

{
	"username": "test",
	"password": "password",
	"name": "Test",
    "email": "test@test.com",
	"role": "USER"
}

###
POST http://localhost:8181/login
content-type: application/json

{
	"username": "test",
	"password": "password"
}
#### Admin ####

GET http://localhost:8181/admin/users

Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huX2RvZSIsImV4cCI6MTU0NzA2NzkxOH0.RsEjrlcYEaKHgb6_0NKG7LgFuNtAshTsnImeGHIfZNV8mz99ZkkRl9yltrnVMRlGoCsPdDWnE70I-Btbe0aztA

DELETE http://localhost:8181/admin/users/:id
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huX2RvZSIsImV4cCI6MTU0NDY5Njc4MH0.c5vs0Z-gCmV83fvMSi-gxQQAUemNK32xi93XIB_Nqt2ekRXllkiXLVBGQgysHQFi4nasry9qVDPM74vmPJ9fLw


### Reservations ###


GET http://localhost:8181/protected/reservations
Authorization: Bearer eyhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNTQ3MTA1Mjg3fQ.POdtc6hFeC0HOcLXakjJymO0wcZroOgMpFHS0jD-t6ncXWTTAJHcKj3X4IVM1okQMSgr-QrIygVc2o55p2vhCg
###
GET http://localhost:8181/protected/reservations/1
###
POST http://localhost:8181/protected/reservations/hotels/3/rooms/37/users/2
content-type: application/json

{
  "number": "123abc",
  "dateFrom": "2019-01-08",
  "dateTo": "2019-01-12"
}
###
PUT http://localhost:8181/protected/reservations/60
content-type: application/json

{
  "dateFrom": "2018-02-22",
  "dateTo": "2018-02-27"
}
###
DELETE http://localhost:8181/protected/reservations/59